name: photo_video_compressor_last
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  image_picker: ^0.8.5+3
  fluttertoast: ^8.0.9
  permission_handler: ^10.0.1
  path_provider: ^2.0.11
  flutter_local_notifications: ^11.0.1
  gallery_saver: ^2.3.2
  video_compress: ^3.1.2
  flutter_image_compress: ^1.1.3
  video_thumbnail: ^0.5.3
  file_picker: ^5.5.0
  video_player: ^2.7.2
  path: ^1.8.3
  awesome_dialog: ^3.1.0
  percent_indicator: ^4.2.3
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
